sudo: false
os:
  - linux
  - osx
arch:
  - amd64
  - ppc64le
language: node_js
node_js:
  - node
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
jobs:
  exclude:
    - arch: ppc64le
      node_js:
        - '0.12'
    - arch: ppc64le
      node_js:
        - '0.10'
